package Telas;

import Controller.ConsultasController;
import Controller.FuncionarioController;
import Controller.LoginController;
import Controller.MateriaisController;
import Controller.PacienteController;
import javax.swing.JFrame;
import unigran.br.projetoodonto.Cadastro.Cadastro;
import unigran.br.projetoodonto.Cadastro.Cadastro;
import unigran.br.projetoodonto.Cadastro.Listagem;
import unigran.br.projetoodonto.Cadastro.CadastroConsulta;
import unigran.br.projetoodonto.Cadastro.CadastroConsulta;
import unigran.br.projetoodonto.Cadastro.CadastroFuncionario;
import unigran.br.projetoodonto.Cadastro.CadastroFuncionario;
import unigran.br.projetoodonto.Cadastro.CadastroLogin;
import unigran.br.projetoodonto.Cadastro.CadastroLogin;
import unigran.br.projetoodonto.Cadastro.CadastroMateriais;
import unigran.br.projetoodonto.Cadastro.CadastroMateriais;
import unigran.br.projetoodonto.Cadastro.CadastroPaciente;
import unigran.br.projetoodonto.Cadastro.CadastroPaciente;
import unigran.br.projetoodonto.Cadastro.Listagem;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadFuncionario = new javax.swing.JMenuItem();
        cadLogin = new javax.swing.JMenuItem();
        consFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadPaciente = new javax.swing.JMenuItem();
        consPaciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cadMateriais = new javax.swing.JMenuItem();
        consMateriais = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        cadConsulta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenu1.setText("Funcionarios");

        cadFuncionario.setText("Cadastro");
        cadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(cadFuncionario);

        cadLogin.setText("Usuario Sistema");
        cadLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadLoginActionPerformed(evt);
            }
        });
        jMenu1.add(cadLogin);

        consFuncionario.setText("Consulta");
        consFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(consFuncionario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pacientes");

        cadPaciente.setText("Cadastro");
        cadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(cadPaciente);

        consPaciente.setText("Consulta");
        jMenu2.add(consPaciente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Materiais");

        cadMateriais.setText("Cadastro");
        cadMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMateriaisActionPerformed(evt);
            }
        });
        jMenu3.add(cadMateriais);

        consMateriais.setText("Consulta");
        jMenu3.add(consMateriais);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Consultas");

        cadConsulta.setText("Cadastro");
        cadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadConsultaActionPerformed(evt);
            }
        });
        jMenu5.add(cadConsulta);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        jMenu6.setText("jMenu6");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("jMenu7");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncionarioActionPerformed
        new Cadastro(null, true, new CadastroFuncionario(), new FuncionarioController()).setVisible(true);
    }//GEN-LAST:event_cadFuncionarioActionPerformed

    private void cadLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadLoginActionPerformed
        new Cadastro(null, true, new CadastroLogin(), new LoginController()).setVisible(true);
    }//GEN-LAST:event_cadLoginActionPerformed

    private void cadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPacienteActionPerformed
        new Cadastro(null, true, new CadastroPaciente(), new PacienteController()).setVisible(true);
    }//GEN-LAST:event_cadPacienteActionPerformed

    private void consFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consFuncionarioActionPerformed
        new Listagem(this, new CadastroPaciente(), new PacienteController()).setVisible(true);
    }//GEN-LAST:event_consFuncionarioActionPerformed

    private void cadMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMateriaisActionPerformed
        new Cadastro(null, true, new CadastroMateriais(), new MateriaisController()).setVisible(true);
    }//GEN-LAST:event_cadMateriaisActionPerformed

    private void cadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadConsultaActionPerformed
        new Cadastro(null, true, new CadastroConsulta(), new ConsultasController()).setVisible(true);
    }//GEN-LAST:event_cadConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new MenuPrincipal();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadConsulta;
    private javax.swing.JMenuItem cadFuncionario;
    private javax.swing.JMenuItem cadLogin;
    private javax.swing.JMenuItem cadMateriais;
    private javax.swing.JMenuItem cadPaciente;
    private javax.swing.JMenuItem consFuncionario;
    private javax.swing.JMenuItem consMateriais;
    private javax.swing.JMenuItem consPaciente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}